#Experiment configuration file.

#PT Lightning trainer arguments.
#Documentation: https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html
#Comment out options you aren't using
train:
  accelerator: "cpu" #str, e.g. "gpu"
  devices: 'auto' #int
  strategy: "ddp" #str
  enable_checkpointing: True #bool
  check_val_every_n_epoch: 1 #int
  default_root_dir: "./lightning_logs" #str
  logger: True #bool
  enable_progress_bar: True #bool
  max_epochs: 5000 #int

#Model arguments
model:
  spatial_dim: 2 #int
  latent_dim: 50 #int
  stages: 1 #int
  loss_fn: "MSELoss" #str, SobolevLoss or loss from torch.nn
  optimizer: "Adam" #str, optimizer from torch.optim
  learning_rate: 0.01 #float

  conv_params:
    in_channels: [1, 4] #list[int]
    out_channels: [4, 4] #list[int]
    bias: [False] #list[bool]

#PT LightningDataModule arguments
data:
  data_dir: "data/ignition_grid" #str
  spatial_dim: 2 #int
  num_points: 2500 #int, mesh only
  batch_size: 8 #int
  channels: [1] #list[int], AE only
  shuffle: True #bool

#Miscellaneous arguments
misc:
  make_gif: False #bool
  compute_stats: True #bool
  early_stopping: False #bool
