name: QuadConv
channels:
  - pytorch
  - nvidia
  - pyg
  - defaults
dependencies:
  - python
  - pytorch
  - pytorch-cuda
  - pytorch-scatter
  - pyg
  - pytorch-cluster
  - scipy
  - yaml
  - matplotlib
  - pip
  - pip:
    - gif
    - torch_tb_profiler
    - pytorch-lightning
